In [0]:
import pandas as pd
#import numpy as np
from nltk.tokenize import word_tokenize 
from nltk.stem import PorterStemmer 

In [0]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [0]:
!pip install numpy==1.16.1
import numpy as np

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
cd drive/My Drive/RecommenderSystems And TopicModelling Lab2

[Errno 2] No such file or directory: 'drive/My Drive/RecommenderSystems And TopicModelling Lab2'
/content/drive/My Drive/RecommenderSystems And TopicModelling Lab2


In [0]:
path="data/"
news_path=path+"nytimes_news_articles.txt"

In [0]:
def parse_url(url):
    date=url[28:38]
    rest_of_url=url[39:]
    category_slash=rest_of_url.find('/')
    category=rest_of_url[:category_slash]
    rest_of_url=rest_of_url[category_slash+1:]
    subcategory="NIL"
    if(rest_of_url.find('/')!=-1):
        subcategory_slash=rest_of_url.find('/')
        subcategory=rest_of_url[:subcategory_slash]    
        rest_of_url=rest_of_url[subcategory_slash+1:]    
    title=rest_of_url[:-5]
    title=title.replace('-',' ')
    return date,category,subcategory,title
    
    
    
    

In [0]:
URL=[]
Date=[]
Article=[]
Category=[]
Subcategory=[]
Title=[]
with open(news_path) as news_file:
    line=news_file.readline()
    while line:
        URL.append(line[5:])
        date_,category_,subcategory_,title_=parse_url(line)
        Date.append(date_)
        Category.append(category_)
        Subcategory.append(subcategory_)
        Title.append(title_)
        #print(title_)
        article_=""
        line=news_file.readline()
        while line and line[:4]!="URL:":
            article_+=line+" "
            line=news_file.readline()
        Article.append(article_[2:].replace('\n',''))    
            

In [0]:
news_df=pd.DataFrame()
news_df['URL']=URL
news_df['Date']=Date
news_df['Category']=Category
news_df['Subcategory']=Subcategory
news_df['Article']=Article
news_df['Title']=Title


In [0]:
del URL,Date,Category,Subcategory,Article,Title

In [0]:
news_df.head()

URL  ...                                              Title
0  http://www.nytimes.com/2016/06/30/sports/baseb...  ...  washington nationals max scherzer baffles mets...
1  http://www.nytimes.com/2016/06/30/nyregion/may...  ...  mayor de blasios counsel to leave next month t...
2  http://www.nytimes.com/2016/06/30/nyregion/thr...  ...  three men charged in killing of cuomo administ...
3  http://www.nytimes.com/2016/06/30/nyregion/tek...  ...  tekserve precursor to the apple store to close...
4  http://www.nytimes.com/2016/06/30/sports/olymp...  ...  once at michael phelpss feet and still chasing...

[5 rows x 6 columns]

In [0]:
category_set=set(Category)
print(len(category_set))

NameError: ignored

In [0]:
subcategory_set=set(Subcategory)
print(len(subcategory_set)-1)

NameError: ignored

In [0]:
stopwords_path=path+"stopwords.txt"

In [0]:
stopwords=[]
with open(stopwords_path) as stopwords_file:
    line=stopwords_file.readline().replace('\n','').replace('-',' ')
    while line:
        stopwords.append(line)
        line=stopwords_file.readline()[:-1].replace('\n','').replace('-',' ')

In [0]:
np.save(path+'stopwords',stopwords)
news_df = pd.read_pickle(path+'news_df')

NameError: ignored

In [0]:
stopwords=np.load(path+'stopwords.npy')
news_df = pd.read_pickle(path+'news_df')

In [0]:
freq_map={}

In [0]:
ps=PorterStemmer()
for article in news_df['Article']:
    word_list=word_tokenize(article)
    article_map={}
    for word in word_list:
        word=word.replace('\n','').replace('-',' ')
        if len(word)>2:
            if word.isalpha():
                if word not in stopwords:
                    word_s=ps.stem(word)
                    if word_s not in stopwords:
                      try :
                        float(word_s.replace(',',''))
                        continue
                      except :  
                        if word_s not in article_map:
                            if word_s in freq_map:
                                freq_map[word_s]+=1
                            else:
                                freq_map[word_s]=1
                            article_map[word_s]=1    

#CHANGED

In [0]:
#freq_map['the']

In [0]:
"the" not in stopwords

False

In [0]:
#freq_map=np.load(path+'freq_map.npy')

In [0]:
np.save(path+'freq_map',freq_map)


In [0]:
#freq_map

In [0]:
len(freq_map)

68953

In [0]:
#news_df = pd.read_pickle(path+'news_df')
#vector_space_table=np.load(path+'vector_space_table.npy')
#freq_map=np.load(path+'freq_map.npy')


In [0]:
freq_map

array({'washington': 1376, 'stellar': 46, 'pitch': 445, 'kept': 698, 'met': 1257, 'afloat': 24, 'first': 4815, 'half': 1355, 'last': 5219, 'season': 1523, 'despit': 1156, 'offens': 482, 'woe': 68, 'but': 5783, 'can': 4972, 'produc': 1163, 'encor': 22, 'pennant win': 1, 'lineup': 268, 'keep': 2001, 'flounder': 22, 'nick': 196, 'bruis': 82, 'stretch': 514, 'thin': 160, 'We': 3714, 'go': 4066, 'ride': 434, 'manag': 2131, 'terri': 202, 'collin': 181, 'said': 7050, 'wednesday': 1543, 'game': 1651, 're': 2657, 'right': 2959, 'now': 4372, 've': 1944, 'got': 1815, 'mani': 4107, 'problem': 1592, 'anything.': 47, '4 2': 44, 'loss': 881, 'nation': 2946, 'cruel': 72, 'already limp': 1, 'steven': 310, 'matz': 39, 'place': 2730, 'spot': 748, 'starter': 219, 'logan': 61, 'verrett': 17, 'allow': 2104, 'two': 5213, 'run': 2635, 'five': 2041, 'inning': 279, 'even': 4340, 'larg': 1892, 'deficit': 190, 'overcom': 190, 'max': 114, 'scherzer': 11, 'give': 2272, 'ourselv': 197, 'chanc': 1021, 'ad': 3020, 'la

In [0]:
number_of_articles=len(news_df)

In [0]:
#d#el vector_space_table
vector_space_table=np.zeros(shape=(number_of_articles,len(freq_map)))

In [0]:
word_to_index={}
index_to_word={}
index=0
for key in freq_map:
  word_to_index[key]=index
  index_to_word[index]=key
  index+=1  

In [0]:
np.save(path+'word_to_index',word_to_index)
np.save(path+'index_to_word',index_to_word)

In [0]:
for i in range(number_of_articles):
  article=news_df['Article'][i]
  word_list=word_tokenize(article)
  article_map={}
  for word in word_list:
    word=word.replace('\n','').replace('-',' ')
    if len(word)>2:
      if word.isalpha():
        if word not in stopwords:
          word_s=ps.stem(word)
          if word_s not in stopwords:
            try :
              float(word_s.replace(',',''))
              continue
            except :  
              if word_s in article_map:
                article_map[word_s]+=1
              else:
                article_map[word_s]=1
  for word in article_map:
    map_index=word_to_index[word]
    freq_art=article_map[word]
    freq_total=freq_map[word]
    vector_space_table[i][map_index]=freq_art
    


In [0]:
vector_space_table=np.load(path+'vector_space_table2.npy')

In [0]:
news_df.to_pickle(path+'news_df')

In [0]:
# news_df = pd.read_pickle(path+'news_df')
# vector_space_table=np.load(path+'vector_space_table.npy')
# freq_map=np.load(path+'freq_map.npy')
# index_to


In [0]:
#vector_space_model=np.load(path+'vector_space_table.npy')

In [0]:
def low_rank_k(mat,num):
    u,s,vh=np.linalg.svd(mat, full_matrices= False)
    u = u[:,:num]
    vh = vh[:num,:]
    s = s[:num]
    s = np.diag(s)
    #my_low_rank = np.dot(np.dot(u,s),vh)
    return u,s,vh



In [0]:
u,s,vh = low_rank_k(vector_space_table,70)

In [0]:
np.save(path+'u',u)
np.save(path+'s',s)
np.save(path+'vh',vh)

In [0]:
u.shape

(8888, 70)

In [0]:
number_of_articles

8888

In [0]:
len(s)

70

(70, 69038)

In [0]:
u[]

In [0]:
np.dot(vector_space_table[:,1],u[:,1])

1.1646757507869534

In [0]:
for i in range(70):
  topic_vector=u[:,i]
  word_list=[]
  for j in range(len(freq_map)):
    current_vector=vector_space_table[:,j]
    val=np.dot(vector_space_table[:,j],u[:,i])
    word_list.append((val,j))
  print("Topic "+str(i+1)+" : ")
  word_list.sort(key=lambda x: x[0],reverse=True)
  for i in range(10):
    print(index_to_word[word_list[i][1]]+",",end='')
  print('\n')  
    
    
    
    

In [0]:
def plsa(vector_space_table,number_of_topics):
  #initialising 
  number_of_terms=len(vector_space_table[0])
  number_of_docs=len(vector_space_table[:,0])
  
  

In [0]:
number_of_articles=len(news_df)

In [0]:
vector_space_table_lda=np.zeros(shape=(number_of_articles,len(freq_map)))

In [0]:
word_to_index={}
index_to_word={}
index=0
for key in freq_map:
  word_to_index[key]=index
  index_to_word[index]=key
  index+=1  

In [0]:
for i in range(number_of_articles):
  article=news_df['Article'][i]
  word_list=word_tokenize(article)
  article_map={}
  for word in word_list:
    word=word.replace('\n','').replace('-',' ')
    if len(word)>2:
      if word.isalpha():
        if word not in stopwords:
          word_s=ps.stem(word)
          try :
            float(word_s.replace(',',''))
            continue
          except :  
            if word_s in article_map:
              article_map[word_s]+=1
            else:
              article_map[word_s]=1
  for word in article_map:
    map_index=word_to_index[word]
    freq_art=article_map[word]
    freq_total=freq_map[word]
    vector_space_table_lda[i][map_index]=freq_art

In [0]:
import random

In [0]:
vec_table=vector_space_table


In [0]:
number_of_topics=100
k=number_of_topics


In [0]:
neta=1
alpha=1

In [0]:

number_of_docs=len(vec_table[:,0])
number_of_terms=len(vec_table[0])
# word_topic_mat=np.zeros(shape=(number_of_terms,number_of_topics))
# doc_topic_mat=np.zeros(shape=(number_of_docs,number_of_topics))  
# topic_mat=np.random.randint(k,size=(number_of_docs,number_of_terms))
# for i in range(number_of_docs):
#   for j in range(number_of_terms):
#     topic=topic_mat[i][j]
#     doc_topic_mat[i][topic]+=vec_table[i][j]
#     word_topic_mat[j][topic]+=vec_table[i][j]
      

    
    
  

In [0]:
np.save(path+'topic_mat',topic_mat)
np.save(path+'doc_topic',doc_topic_mat)
np.save(path+'word_topic',word_topic_mat)

In [0]:
topic_mat=np.load(path+'topic_mat.npy')
doc_topic_mat=np.load(path+'doc_topic.npy')
word_topic_mat=np.load(path+'word_topic.npy')

In [0]:
doc_word_map={}
for i in range(number_of_docs):
  doc_word_map[i]=[]
  for j in range(number_of_terms):
    if(vec_table[i][j]>0):
      doc_word_map[i].append(j)
      

In [0]:
np.save(path+'doc_word_map',doc_word_map)

In [0]:
sum_array=np.zeros(number_of_terms)
for i in range(number_of_terms):
  sum_array[i]=sum(vec_table[:,i])

In [0]:
for k in range(5):
  print(k)
  if(k!=0 and k%2==0):
    np.save(path+'topic_mat',topic_mat)
    np.save(path+'doc_topic',doc_topic_mat)
    np.save(path+'word_topic',word_topic_mat) 
  for i in range(number_of_docs):
    if(i%400==0):
      print(i)
    num_of_terms=sum(vec_table[i])
    for j in doc_word_map[i]:
      p_final=0
      init_topic=topic_mat[i][j]
      topic_final=topic_mat[i][j]
      for topic in range(number_of_topics):
        #topic=topic_mat[i][j]
        num_terms=num_of_terms-vec_table[i][j]+number_of_topics*alpha
        num_terms_assigned=doc_topic_mat[i][topic]-vec_table[i][j]+alpha
        if(num_terms!=0):
          p1=num_terms_assigned/num_terms
        else:
          p1=0
          
        num_term_in_all_docs=sum_array[j]-vec_table[i][j]+number_of_terms*neta
        num_term_with_this_topic=word_topic_mat[j][topic]-vec_table[i][j]+neta
        if(num_term_in_all_docs!=0):
          p2=num_term_with_this_topic/num_term_in_all_docs
        else:    
          p2=0
        p_final1=p1*p2
        if(p_final1>p_final):
          p_final=p_final1
          topic_final=topic
      word_topic_mat[j][init_topic]-=  vec_table[i][j]
      doc_topic_mat[i][init_topic]-= vec_table[i][j]
      word_topic_mat[j][topic_final]+=  vec_table[i][j]
      doc_topic_mat[i][topic_final]+= vec_table[i][j] 
      topic_mat[i][j]=topic_final
      
        
      

0
0
400
800
1200
1600
2000
2400
2800
3200
3600
4000
4400
4800
5200
5600
6000
6400
6800
7200
7600
8000
8400
8800
1
0
400
800
1200
1600
2000
2400
2800
3200
3600
4000
4400
4800
5200
5600
6000
6400
6800
7200
7600
8000
8400
8800
2
0
400
800
1200
1600
2000
2400
2800
3200
3600
4000
4400
4800
5200
5600
6000
6400
6800
7200
7600
8000
8400
8800
3
0
400
800
1200
1600
2000
2400
2800
3200
3600
4000
4400
4800
5200
5600
6000
6400
6800
7200
7600
8000
8400
8800
4
0
400
800
1200
1600
2000
2400
2800
3200
3600
4000
4400
4800
5200
5600
6000
6400
6800
7200
7600
8000
8400
8800


In [0]:

for k in range(number_of_topics):
  print("Topic "+ str(k+1)+" :")
  ids=word_topic_mat[:,k].argsort()
  for j in range (1,10):
    print(index_to_word[ids[-j]]+", ",end='')
  print('\n')  

Topic 1 :
said, season, room, problem, washington, new, discuss, will, year, 

Topic 2 :
dean, reson, collector, acceler, palac, steer, casual, lifetim, automak, 

Topic 3 :
game, sixth, first, percent, starter, andrew, team, european, run, 

Topic 4 :
quietli, loom, nevertheless, wipe, gown, berkeley, frighten, biologist, ate, 

Topic 5 :
sang, interrupt, produc, backdrop, unrel, rever, linda, hunger, recur, 

Topic 6 :
said, year, one, new, like, will, time, state, can, 

Topic 7 :
wise, honest, implement, retriev, tens, horribl, worship, beg, stomach, 

Topic 8 :
outdoor, ourselv, rigor, therefor, coastal, hung, victorian, levinson, shomrim, 

Topic 9 :
wa, chaotic, nicknam, whitley, corinthian, helm, panton, apt, puerto, 

Topic 10 :
said, one, year, new, will, like, time, state, trump, 

Topic 11 :
cohn, willerslev, pult, black, pappa, uber, kalin, handwritten, fan, 

Topic 12 :
ballet, zappa, rio, bow, lettuc, chapman, tillman, sugar, mannatech, 

Topic 13 :
ourselv, percent, war

In [0]:
for k in range(50):
  print(k)
  if(k!=0 and k%4==0):
    np.save(path+'topic_mat',topic_mat)
    np.save(path+'doc_topic',doc_topic_mat)
    np.save(path+'word_topic',word_topic_mat) 
  if(k!=0 and k % 5==0):
    
    for a in range(number_of_topics):
      print("Topic "+ str(a+1)+" :")
      ids=word_topic_mat[:,a].argsort()
      for j in range (1,11):
        print(index_to_word[ids[-j]]+", ",end='')
      print('\n')  

for k in range(number_of_topics):
  print("Topic "+ str(k+1)+" :")
  ids=word_topic_mat[:,k].argsort()
  for j in range (1,10):
    print(index_to_word[ids[-j]]+", ",end='')
  print('\n')      
    
  for i in range(number_of_docs):
    if(i%400==0):
      print(i)
    num_of_terms=sum(vec_table[i])
    for j in doc_word_map[i]:
      p_final=0
      init_topic=topic_mat[i][j]
      topic_final=topic_mat[i][j]
      for topic in range(number_of_topics):
        #topic=topic_mat[i][j]
        num_terms=num_of_terms-vec_table[i][j]+number_of_topics*alpha
        num_terms_assigned=doc_topic_mat[i][topic]-vec_table[i][j]+alpha
        if(num_terms!=0):
          p1=num_terms_assigned/num_terms
        else:
          p1=0
          
        num_term_in_all_docs=sum_array[j]-vec_table[i][j]+number_of_terms*neta
        num_term_with_this_topic=word_topic_mat[j][topic]-vec_table[i][j]+neta
        if(num_term_in_all_docs!=0):
          p2=num_term_with_this_topic/num_term_in_all_docs
        else:    
          p2=0
        p_final1=p1*p2
        if(p_final1>p_final):
          p_final=p_final1
          topic_final=topic
      word_topic_mat[j][init_topic]-=  vec_table[i][j]
      doc_topic_mat[i][init_topic]-= vec_table[i][j]
      word_topic_mat[j][topic_final]+=  vec_table[i][j]
      doc_topic_mat[i][topic_final]+= vec_table[i][j] 
      topic_mat[i][j]=topic_final
       

0
1
2
3
4


In [0]:
vector_space_table

array([[2., 1., 8., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 4., 1., 2.]])

In [0]:
word_topic_mat

array([[ -7.98281969,  -5.19312788, -12.77251151, ..., -10.98281969,
        -11.25177707, -14.36907545],
       [ -3.26381593,   0.        ,   0.        , ...,   0.        ,
          0.        ,  -4.26381593],
       [-19.94383049, -21.93821354,  -3.9887661 , ...,  -1.99438305,
        -31.91012879, -43.87642708],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ]])

In [0]:
dfg=np.array([1,2,3,4])

In [0]:
dfg.argsort()

array([0, 1, 2, 3])

In [0]:
topic_mat[0:1].argsort()

array([[42147, 52682, 13898, ..., 66924,  8496, 28827]])

In [0]:
topic_mat[0][42147]

0